name: adfc_ttp
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  xml: ^6.5.0
  path: ^1.9.0
  csv: ^5.1.1
  dart_date: ^1.3.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
